### ISSUE TITLE
Connection UI does not refresh when connect to Sovrin Cloud Agent does not complete.

### ISSUE THREAD

**Issue by ken-ebert** [sovrin-foundation/aries-toolbox#17]
In the Aries Toolbox,
on the connections tab,
when I copy the invitation url "https://agent.sovrin.org/?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiNjBhNjY1OGUtMDYzZS00MTcyLWIyN2ItZmZlYzJjMzY2N2ZiIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2FnZW50LnNvdnJpbi5vcmcvIiwgImxhYmVsIjogIlNvdnJpbiBBZ2VudCIsICJyZWNpcGllbnRLZXlzIjogWyIzR3p2NEhZb2ZXNUp5WGd2YzdBeGVhNmVVWkdkTEJ1Rk43NHRjVzVmb0gxRyJdfQ=="
into "Add connection from invitation:" and
click "Add Agent",
and nothing happens in the UI.
If I reload,
the "Sovrin Agent" goes into the "Pending Connections:" and never completes.

**Comment by burdettadam** [comment]
I have added code that clears the input form so it is clear the invite was "scanned" as well as a timer that refreshes the connection list after 4 seconds. This should make for a better experience. The sovrin invite is using https, but does not have a  valid certificate, so the invite fails. More work is needed on the back end for the connection to complete.

**Comment by burdettadam** [comment]
@ken-ebert, Please test.
