### ISSUE TITLE
Holder undefined

### ISSUE THREAD

**Issue by lynnbendixsen** [sovrin-foundation/aries-toolbox#41]
# Summary
The "Holder undefined" title needs changed to be more clear.

## Definition (optional)
On the Verifications tab, whenever a verification shows up in the list the words "Holder undefined" appear.  That title is unclear and indiscernible between the different items in the list.  I think that this shows up in Activity 5.B and in Activity 2.B.4

**Comment by burdettadam** [comment]
resolved in pr #62
