### ISSUE TITLE
Verification process never completes

### ISSUE THREAD

**Issue by lynnbendixsen** [sovrin-foundation/aries-toolbox#43]
# Summary
The Verification gets to a "request_sent" state but doesn't ever progress past that on my box.

## Definition (optional)
See Activity 5 (among others)

**Comment by lynnbendixsen** [comment]
Looks like it got to "verified" this time.  Maybe this is situation dependent?  Got to verified after requesting a first_name/last_name verification from my own Company to my own Holder.

**Comment by lynnbendixsen** [comment]
I will leave this open for now in case I see the issue again in a different scenario, But it is now a much lower priority to look at.

**Comment by burdettadam** [comment]
I submitted a pr yesterday ,#40, that I think corrected this. we were calling the wrong API to get the updated list.
