### ISSUE TITLE
MUST click on the default item

### ISSUE THREAD

**Issue by lynnbendixsen** [sovrin-foundation/aries-toolbox#44]
# Summary
When an item shows up as the default (i.e. credential definition) sometimes "You MUST click the correct item, even if the correct item appears in the window" before any of the fields appear that need to be filled in.  Tabbing to the item and hitting enter doesn't even work.  You must click.

## Definition (optional)
Activity 1.E.5.c

**Comment by burdettadam** [comment]
does #58 correct this issue?
